
version: '3.4'

services:
  savefileparseapi2:
    image: savefileparseapi2
    build:
      context: .
      dockerfile: SaveFileParseAPI2/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 80:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development        
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
