
version: '3.4'

services:
  savefileparseapi2:
    image: savefileparseapi2
    restart: unless-stopped
    build:
      context: .
      dockerfile: SaveFileParseAPI2/Dockerfile
    ports:
      - 5000:5000
    environment:
      - STOPCOUNT=100
    